---
title: "Compare excess death in va and CDC data"
author: "Dan Weinberger"
date: "10/29/2020"
output:
  html_document:
    df_print: paged
    html_document: null
    toc: yes
    toc_depth: 2
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document: 
    keep_tex:  true
params:
  agg.level: 'state'
  n.days.filter: 20
  web.version: FALSE
  extrap.date: '2020-01-26'
  count.start.date: '2020-03-01'
  end.data.date: '2020-09-05'
---

```{r, include = F}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo=F,
  warning=FALSE, 
  message=FALSE,
  comment = "#>",
  dev=c('png','pdf'),
  fig.path='./figures/',
  gganimate = list(
    nframes = 50)
)

```

```{r setup}
library(readxl)
library(cdcfluview)
library(reshape2)
library(ggplot2)
library(lubridate)
library(RColorBrewer)
library(plotly)
library(MMWRweek)
library(readr)
library(rjson)
library(parallel)
library(htmlTable)
library(RSocrata)
library(pdftools)
library(readr)
library(patchwork)
library(abind)
library(INLA)
library(gsubfn)
library(dplyr)
library(RCurl)
library(dplyr)
library(tidyverse)
library(gifski)
library(gganimate)
library(shiny)
library(INLA)
library(lme4)

library(pbapply)
#library(jsonlite)
set.seed(123)

source('./R/read_dependent_scripts.R')

```


```{r}

cdc<- readRDS('./outputs/summary_list_cdc.rds')
va<- readRDS('./outputs/summary_list_va.rds')

```

```{r}
preds.age <- bind_rows(cdc$preds.age, va$preds.age)

 p1 <- RR_plot(ds=preds.age ) + 
    facet_wrap(~agec, scales='fixed')
 
 p1
```
```{r, fig.width=8, fg.height=12}
preds.age.race.region <- bind_rows(cdc$preds.age.race.region, va$preds.age.race.region)

 p2 <- RR_plot(ds=preds.age.race.region[preds.age.race.region$race_recode==1 & preds.age.race.region$sex=='M',] ,datemin='2020-01-01') + 
    facet_grid(region~agec, scales='fixed')
 
 p2
```


```{r}

excess.ds <- preds.age %>%
  select(source, agec, date, starts_with('excess_inc')) %>%
  mutate(excess_inc = paste0(round(excess_inc_median, 1) , ', (' ,round(excess_inc_lcl, 1) , ', ', round(excess_inc_ucl, 1) , ')'  )    )

excess.ds.m <- melt(excess.ds[,c('source','agec','date','excess_inc')], id.vars=c('source','agec','date'))
excess.ds.c <- dcast(excess.ds.m, agec+ date ~ source)

htmlTable(excess.ds.c[excess.ds.c$date>='2020-01-01',c('date','cdc','va')],
          n.rgroup=c(4,4,4,4,4), rgroup=unique(excess.ds.c$agec), rnames=F,
          caption='Table 2: Excess Deaths per 100,000 population')
```

```{r}

excess.ds.age.region <- preds.age.race.region %>%
  select(source, agec,region,sex,race_recode, date, starts_with('excess_inc')) %>%
  mutate(excess_inc = paste0(round(excess_inc_median, 1) , ', (' ,round(excess_inc_lcl, 1) , ', ', round(excess_inc_ucl, 1) , ')'  )    )

excess.ds.age.region.m <- melt(excess.ds.age.region[,c('source','agec','sex','race_recode','region','date','excess_inc')], id.vars=c('source','agec','date', 'sex', 'region','race_recode'))

excess.ds.age.region.c <- dcast(excess.ds.age.region.m, agec+ sex+region + date +race_recode ~ source)

htmlTable(excess.ds.age.region.c[excess.ds.age.region.c$date>='2020-01-01' & excess.ds.age.region.c$race_recode==1 & excess.ds.age.region.c$sex=='M' & excess.ds.age.region.c$region=='Northeast',c('date','cdc','va')],
          n.rgroup=c(4,4,4,4,4), rgroup=unique(excess.ds.c$agec), rnames=F,
          caption='Table 2: Excess Deaths per 100,000 population in the Northeast, White, males')


```


